### ISSUE TITLE
Code review: Dispute reason enum mispelled

### ISSUE THREAD

**Issue by IDisposable** [xamarin/XamarinStripe#4]
In StripeDisputeReason.cs, line 11.

https://github.com/xamarin/XamarinStripe/blob/master/XamarinStripe/StripeDisputeReason.cs#L11

``` C#
    public enum StripeDisputeReason {
        Duplucate,
```

The **Duplucate** should be **Duplicate**

**Comment by lewing** [comment]
Fixed in fb3ac0a7e0608734b74a4f2c6dae483b371a4ccc
